### ISSUE TITLE
tried it out on jsfiddle 

### ISSUE THREAD

**Issue by vitalijalbu** [CodyHouse/cd-flexi-header-changelog#1]
Hi, I tried it nav on jsfiddle, but seems on mobile it's not working... Nav remains collapsed and button to collapse the menu isn't visible. can uplease share a clear example? Thanks

**Comment by claudia-romano** [comment]
Hi there, if you are creating your custom example, please make sure you are importing the CSS/JS files of the framework and make sure you are including the `script` for progressive enhancement, as explained on our Documentation page:
https://codyhouse.co/ds/docs/framework#download
https://codyhouse.co/ds/docs/framework#progressive-enhancement

Cheers!

**Comment by vitalijalbu** [comment]
here is an example: https://codepen.io/vitalijalbu/pen/OJjOZNe   as u can
see on mobile device menu doesn't toggle
maybe i forgot something!?

Il giorno mar 2 nov 2021 alle ore 12:57 Claudia Romano <
***@***.***> ha scritto:

**Comment by claudia-romano** [comment]
The flexi header has some dependencies that you should include. You can find them here:
https://codyhouse.co/ds/components/info/flexi-header

In your demo, you are not including those components and this is why the menu is not working. Make sure to include the SCSS/JS of those dependencies as well and your problem should be fixed. Cheers.

**Comment by vitalijalbu** [comment]
Not working yet, tried also on localhost... pls see my codepen, all is
included.

Il giorno mer 3 nov 2021 alle ore 16:15 Claudia Romano <
***@***.***> ha scritto:

**Comment by sebastiano-guerriero** [comment]
I just checked but the two dependencies (Animated menu button and Search input) have not been imported.

More info here: https://codyhouse.co/ds/components/info/flexi-header
