### ISSUE TITLE
Flexi header dropdown issue

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-flexi-header-changelog#2]
Hy,

please see screen recording.

Thanks

![flexi header](https://user-images.githubusercontent.com/5861215/164215502-f5968ac2-0b97-4bda-b89b-8501b205c9b9.gif)

**Comment by sebastiano-guerriero** [comment]
Hi Dario, I've just pushed a fix (see image attached - it's inside the medium breakpoint)
<img width="673" alt="Screenshot 2022-04-20 at 15 21 39" src="https://user-images.githubusercontent.com/5512742/164239874-e423bcef-6933-4b65-b60d-c5f835f8c006.png">
.
